# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francy/Desktop/RealTimeDeltaQSD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francy/Desktop/RealTimeDeltaQSD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francy/Desktop/RealTimeDeltaQSD/CMakeFiles /home/francy/Desktop/RealTimeDeltaQSD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francy/Desktop/RealTimeDeltaQSD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RealTimeDeltaQSD

# Build rule for target.
RealTimeDeltaQSD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RealTimeDeltaQSD
.PHONY : RealTimeDeltaQSD

# fast build rule for target.
RealTimeDeltaQSD/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RealTimeDeltaQSD.dir/build.make src/CMakeFiles/RealTimeDeltaQSD.dir/build
.PHONY : RealTimeDeltaQSD/fast

#=============================================================================
# Target rules for targets named RealTimeDeltaQSD_autogen_timestamp_deps

# Build rule for target.
RealTimeDeltaQSD_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RealTimeDeltaQSD_autogen_timestamp_deps
.PHONY : RealTimeDeltaQSD_autogen_timestamp_deps

# fast build rule for target.
RealTimeDeltaQSD_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RealTimeDeltaQSD_autogen_timestamp_deps.dir/build.make src/CMakeFiles/RealTimeDeltaQSD_autogen_timestamp_deps.dir/build
.PHONY : RealTimeDeltaQSD_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named RealTimeDeltaQSD_autogen

# Build rule for target.
RealTimeDeltaQSD_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RealTimeDeltaQSD_autogen
.PHONY : RealTimeDeltaQSD_autogen

# fast build rule for target.
RealTimeDeltaQSD_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/RealTimeDeltaQSD_autogen.dir/build.make src/CMakeFiles/RealTimeDeltaQSD_autogen.dir/build
.PHONY : RealTimeDeltaQSD_autogen/fast

#=============================================================================
# Target rules for targets named DQ_dashboard

# Build rule for target.
DQ_dashboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_dashboard
.PHONY : DQ_dashboard

# fast build rule for target.
DQ_dashboard/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/DQ_dashboard.dir/build.make src/dashboard/CMakeFiles/DQ_dashboard.dir/build
.PHONY : DQ_dashboard/fast

#=============================================================================
# Target rules for targets named dashboard

# Build rule for target.
dashboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dashboard
.PHONY : dashboard

# fast build rule for target.
dashboard/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/dashboard.dir/build.make src/dashboard/CMakeFiles/dashboard.dir/build
.PHONY : dashboard/fast

#=============================================================================
# Target rules for targets named DQ_dashboard_autogen_timestamp_deps

# Build rule for target.
DQ_dashboard_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_dashboard_autogen_timestamp_deps
.PHONY : DQ_dashboard_autogen_timestamp_deps

# fast build rule for target.
DQ_dashboard_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/DQ_dashboard_autogen_timestamp_deps.dir/build.make src/dashboard/CMakeFiles/DQ_dashboard_autogen_timestamp_deps.dir/build
.PHONY : DQ_dashboard_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named DQ_dashboard_autogen

# Build rule for target.
DQ_dashboard_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_dashboard_autogen
.PHONY : DQ_dashboard_autogen

# fast build rule for target.
DQ_dashboard_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/DQ_dashboard_autogen.dir/build.make src/dashboard/CMakeFiles/DQ_dashboard_autogen.dir/build
.PHONY : DQ_dashboard_autogen/fast

#=============================================================================
# Target rules for targets named dashboard_autogen_timestamp_deps

# Build rule for target.
dashboard_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dashboard_autogen_timestamp_deps
.PHONY : dashboard_autogen_timestamp_deps

# fast build rule for target.
dashboard_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/dashboard_autogen_timestamp_deps.dir/build.make src/dashboard/CMakeFiles/dashboard_autogen_timestamp_deps.dir/build
.PHONY : dashboard_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named dashboard_autogen

# Build rule for target.
dashboard_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dashboard_autogen
.PHONY : dashboard_autogen

# fast build rule for target.
dashboard_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/dashboard/CMakeFiles/dashboard_autogen.dir/build.make src/dashboard/CMakeFiles/dashboard_autogen.dir/build
.PHONY : dashboard_autogen/fast

#=============================================================================
# Target rules for targets named DQ_diagram

# Build rule for target.
DQ_diagram: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_diagram
.PHONY : DQ_diagram

# fast build rule for target.
DQ_diagram/fast:
	$(MAKE) $(MAKESILENT) -f src/diagram/CMakeFiles/DQ_diagram.dir/build.make src/diagram/CMakeFiles/DQ_diagram.dir/build
.PHONY : DQ_diagram/fast

#=============================================================================
# Target rules for targets named diagram

# Build rule for target.
diagram: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diagram
.PHONY : diagram

# fast build rule for target.
diagram/fast:
	$(MAKE) $(MAKESILENT) -f src/diagram/CMakeFiles/diagram.dir/build.make src/diagram/CMakeFiles/diagram.dir/build
.PHONY : diagram/fast

#=============================================================================
# Target rules for targets named DQ_maths

# Build rule for target.
DQ_maths: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_maths
.PHONY : DQ_maths

# fast build rule for target.
DQ_maths/fast:
	$(MAKE) $(MAKESILENT) -f src/maths/CMakeFiles/DQ_maths.dir/build.make src/maths/CMakeFiles/DQ_maths.dir/build
.PHONY : DQ_maths/fast

#=============================================================================
# Target rules for targets named maths

# Build rule for target.
maths: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 maths
.PHONY : maths

# fast build rule for target.
maths/fast:
	$(MAKE) $(MAKESILENT) -f src/maths/CMakeFiles/maths.dir/build.make src/maths/CMakeFiles/maths.dir/build
.PHONY : maths/fast

#=============================================================================
# Target rules for targets named DQ_server

# Build rule for target.
DQ_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DQ_server
.PHONY : DQ_server

# fast build rule for target.
DQ_server/fast:
	$(MAKE) $(MAKESILENT) -f src/server/CMakeFiles/DQ_server.dir/build.make src/server/CMakeFiles/DQ_server.dir/build
.PHONY : DQ_server/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f src/server/CMakeFiles/server.dir/build.make src/server/CMakeFiles/server.dir/build
.PHONY : server/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DQ_dashboard_autogen"
	@echo "... DQ_dashboard_autogen_timestamp_deps"
	@echo "... RealTimeDeltaQSD_autogen"
	@echo "... RealTimeDeltaQSD_autogen_timestamp_deps"
	@echo "... dashboard_autogen"
	@echo "... dashboard_autogen_timestamp_deps"
	@echo "... DQ_dashboard"
	@echo "... DQ_diagram"
	@echo "... DQ_maths"
	@echo "... DQ_server"
	@echo "... RealTimeDeltaQSD"
	@echo "... dashboard"
	@echo "... diagram"
	@echo "... maths"
	@echo "... server"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

